### ISSUE TITLE
How can I add an image to my blog on topjavablogs.com?

### ISSUE THREAD

**Issue by stephanrauh** [jirkapinkas/java-blog-aggregator#3]
Hi Jirka,

I didn't find any contact information on topjavablogs.com, so I'll open an issue to contact you. I've noticed that some blogs have an image - usually the headshot of the blogger. How can I add an image to my blog on topjavablogs.com?

Regards,
Stephan

**Comment by jirkapinkas** [comment]
Hello Stephan, right now only me (the administrator) can add and approve the icons. Send me the image to: jirka.pinkas@gmail.com and the name of the blog it should be assigned to. Images are in format: PNG, 50x50 pixels. If you send it in different format, I will convert it manually. 

Thanks. 

Jirka.
